export const professions = [
    "Accountant",
    "Actress",
    "Architect",
    "Astronomer",
    "Author",
    "Baker",
    "Bricklayer",
    "Bus driver",
    "Butcher",
    "Carpenter",
    "Chef",
    "Cleaner",
    "Coder",
    "Consultant",
    "Dentist",
    "Designer",
    "DevOps specialist",
    "Doctor",
    "Dustman",
    "Electrician",
    "Engineer",
    "Factory worker",
    "Farmer",
    "Fire fighter",
    "Fisherman",
    "Florist",
    "Gardener",
    "Hairdresser",
    "Journalist",
    "Judge",
    "Lawyer",
    "Lecturer",
    "Librarian",
    "Lifeguard",
    "Mechanic",
    "Model",
    "Newsreader",
    "Nurse",
    "Optician",
    "Painter",
    "Pharmacist",
    "Photographer",
    "Physician",
    "Pilot",
    "Plumber",
    "Pointy-haired boss",
    "Politician",
    "Postman",
    "Product Owner",
    "Real estate agent",
    "Receptionist",
    "Scientist",
    "Scrum master",
    "Secretary",
    "Shop assistant",
    "Tailor",
    "Taxi driver",
    "Teacher",
    "Tester",
    "Translator",
    "Traffic warden",
    "Travel agent",
    "Vet",
    "UNIX guru",
    "Waiter/Waitress",
    "Window cleaner",
]

export function randomProfession() {
    return professions[Math.floor(Math.random() * professions.length)]
}
