export const professions = [
    'Accountant',
    'Actress',
    'Architect',
    'Astronomer',
    'Author',
    'Baker',
    'Bricklayer',
    'Bus driver',
    'Butcher',
    'Carpenter',
    'Chef',
    'Cleaner',
    'Dentist',
    'Designer',
    'Doctor',
    'Dustman',
    'Electrician',
    'Engineer',
    'Factory worker',
    'Farmer',
    'Fire fighter',
    'Fisherman',
    'Florist',
    'Gardener',
    'Hairdresser',
    'Journalist',
    'Judge',
    'Lawyer',
    'Lecturer',
    'Librarian',
    'Lifeguard',
    'Mechanic',
    'Model',
    'Newsreader',
    'Nurse',
    'Optician',
    'Painter',
    'Pharmacist',
    'Photographer',
    'Pilot',
    'Plumber',
    'Politician',
    'Postman',
    'Real estate agent',
    'Receptionist',
    'Scientist',
    'Secretary',
    'Shop assistant',
    'Soldier',
    'Tailor',
    'Taxi driver',
    'Teacher',
    'Translator',
    'Traffic warden',
    'Travel agent',
    'Vet',
    'Waiter/Waitress',
    'Window cleaner'
]

export function randomProfession() {
    return professions[Math.floor(Math.random() * professions.length)]
}